### ISSUE TITLE
Improve Gitlab CI pipeline

### ISSUE THREAD

**Issue by mohoff** [strong-config/node#13]
Once we are making use of the new `extend` keyword in the `.gitlab-ci.yml` in our pipeline files, let's adopt the pipeline setup of this project accordingly.

The goal is to have
- efficient pipelines than run fast and make use of caching strategies via optimal configurations for `cache` and `artificats`
- Simplify and DRY out the yaml

**Comment by chapati23** [comment]
My original point in the first PR about `artifacts` was the question: Do we actually need any artifacts here? If yes, what for?

**Comment by mohoff** [comment]
Yes, artifacts should be created by the build job and consumed by the release job.

**Comment by chapati23** [comment]
ok, theoretically understood.

but practically our `build_npm_package` and `release` jobs are [part of the same pipeline](https://git.brickblock.sh/devops/strong-config-ts-mirror/pipelines/22076) so we shouldn't need any artifacts because we don't need a later pipeline to access an earlier pipeline's output or am i missing something?

**Comment by mohoff** [comment]
This could be done with `cache` instead, yes. 

However, I wanted to use the primitives as recommended https://docs.gitlab.com/ee/ci/caching/#cache-vs-artifacts

**Comment by chapati23** [comment]
Ah, I see. Fair point. TIL 🤓

> While the cache can be abused to pass intermediate build results between stages, there may be cases where artifacts are a better fit.
