### ISSUE TITLE
Make top-level export a Class `StrongConfig`

### ISSUE THREAD

**Issue by mohoff** [strong-config/node#7]
Currently, we export an object with `{ load, validate }` properties. Instead, we want to export a class named `StrongConfig` that accepts as configuration obj as a constructor argument. Members would expose existing `load()` and `validate()` functionality.

**Comment by chapati23** [comment]
What's the advantage of this over the current approach?

**Comment by mohoff** [comment]
That we can initialize a global strong-config state with `(new StrongConfig(options)).load()`.

Currently, there's no way to pass `options`. `load()` could take a param, but `options` is designed to contain global state that is not necessarily related to `load()`.

**Comment by chapati23** [comment]
Hmm, not fully convinced of this idea yet. Why is it not sufficient to have `load()` accept an `options` param?

**Comment by mohoff** [comment]
Why is `load(option)` better than `(new StrongConfig(options)).load()`? As I said, the `options` are not specific to loading functionality but overall configure and intialize strong-config.

That's why I think the constructor is the correct place to pass `options`.

**Comment by chapati23** [comment]
To be honest, it's more of a general aversion against classes because i'm so used to the functional way in JS now. Can't think of any other areas in our code where we need to initialise a class to do something.

Let's maybe discuss this in context of how `strong-config` is actually used.

Currently we're doing this in every file that requires config values, right?

```js
const config = require('@brickblock/strong-config').load()
console.log("Some config value: ", config.value")
```

In your example I think this would become:

```js
const StrongConfig = require('@brickblock/strong-config')
const config = new StrongConfig().load()
console.log("Some config value: ", config.value")
```

Which is one more line of code.

Plus, I think what bothers me a bit is that `new StrongConfig()` sounds like we're somehow instantiating a new singleton here when in reality we're loading the same memoized state that we've initialised on the first `load()`. It looks like duck, but it doesn't quack like a duck 🦆

Hope this made my point a little clearer.

**Comment by mohoff** [comment]
How about 

```js
//config.js
import StrongConfig from '@strong-config/node'
const config = new StrongConfig(config).load()
export default config

//app.js
import config from './config

console.log(config.value)
```

**Comment by chapati23** [comment]
Worth a shot. But due to the async nature of the `load()` function, I'm not 100% sure this would work. Because it could be that `const config = new StrongConfig(config).load()` would run too early?

Not sure, we can try it out :)

**Comment by mohoff** [comment]
Alright!

`load()` is not async, we explicitly use all the `fs.*sync` functions to make it sync and thus callable without being wrapped in an `async` function.

**Comment by chapati23** [comment]
true, we switched that, already forgot about that! ok then let's give it a shot, should just verify whether the `fs.readFileSync()` is really just executed once, because i believe it's still a relatively expensive operation
